import type { Metadata } from "next";
import "./globals.css";
import { Inter, Noto_Sans } from 'next/font/google';
import { FloatingDock } from "@/components/FloatingDock/FloatingDock";
import { FloatingDockLinks } from "@/components/FloatingDock/DockItems";
import Navbar from "@/components/Navbar/Navbar";
import ThemeWrapper from "@/components/ThemeWrapper/themeWrapper";

const inter = Noto_Sans({
  subsets: ['latin'],
  style: ['normal', 'italic'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased  text-zinc-700 dark:text-neutral-400`}
      >
        <ThemeWrapper>
          <Navbar />
          <div className="px-6 md:px-20 lg:px-0 lg:max-w-4xl mx-auto">
            {children}
            <FloatingDock
              items={FloatingDockLinks}
            />
          </div>
          <p className="text-[.55rem] md:text-[.65rem] lg:text-xs mt-12 md:mt-20 mb-1 md:ml-2 text-center md:text-left">No © copyright issues. Feel free to copy whatever you like. Here's the <span className="underline font-semibold"> code</span>.</p>
        </ThemeWrapper>
      </body>
    </html>
  );
}
